package dk.itu.mario.level;

import java.util.Random;

import dk.itu.mario.MarioInterface.Constraints;
import dk.itu.mario.MarioInterface.GamePlay;
import dk.itu.mario.MarioInterface.LevelInterface;
import dk.itu.mario.engine.sprites.SpriteTemplate;
import dk.itu.mario.engine.sprites.Enemy;

public class MyLevel extends Level
{
    private static long lastSeed;
    private static Random levelSeedRandom;

    private int difficulty;
    private int type;

    public MyLevel(int width, int height)
    {
        super(width, height);
    }

    public MyLevel(int width, int height, long seed, int difficulty, int type, GamePlay playerMetrics)
    {
        this(width, height);
        this.difficulty = difficulty;
        this.type = type;
        lastSeed = seed;
        levelSeedRandom = new Random(seed);

        setBlock(0, 14, GROUND);
        setBlock(0, 13, GROUND);
        setBlock(0, 12, GROUND);
        setBlock(0, 11, GROUND);
        setBlock(1, 12, BLOCK_EMPTY);
        setBlock(1, 14, GROUND);
        setBlock(2, 12, BLOCK_EMPTY);
        setBlock(2, 13, GROUND);
        setBlock(2, 14, GROUND);
        setBlock(3, 12, BLOCK_EMPTY);
        setBlock(3, 13, GROUND);
        setBlock(4, 12, BLOCK_EMPTY);
        setBlock(4, 13, GROUND);
        setBlock(4, 14, GROUND);
        setBlock(5, 12, BLOCK_EMPTY);
        setBlock(5, 13, GROUND);
        setBlock(5, 14, GROUND);
        setBlock(6, 12, BLOCK_EMPTY);
        setBlock(6, 13, GROUND);
        setBlock(6, 14, GROUND);
        setBlock(7, 12, BLOCK_EMPTY);
        setBlock(7, 13, GROUND);
        setBlock(7, 14, GROUND);
        setBlock(8, 12, BLOCK_EMPTY);
        setBlock(8, 13, GROUND);
        setBlock(8, 14, GROUND);
        setBlock(9, 12, BLOCK_EMPTY);
        setBlock(9, 13, GROUND);
        setBlock(9, 14, GROUND);
        setBlock(10, 12, BLOCK_EMPTY);
        setBlock(10, 13, GROUND);
        setBlock(10, 14, GROUND);
        setBlock(11, 12, BLOCK_EMPTY);
        setBlock(11, 13, GROUND);
        setBlock(11, 14, GROUND);
        setBlock(12, 12, BLOCK_EMPTY);
        setBlock(12, 13, GROUND);
        setBlock(12, 14, GROUND);
        setBlock(13, 12, BLOCK_EMPTY);
        setBlock(13, 13, GROUND);
        setBlock(13, 14, GROUND);
        setBlock(14, 12, BLOCK_EMPTY);
        setBlock(14, 13, GROUND);
        setBlock(14, 14, GROUND);
        setBlock(15, 12, BLOCK_EMPTY);
        setBlock(15, 13, GROUND);
        setBlock(15, 14, GROUND);
        setBlock(16, 12, BLOCK_EMPTY);
        setBlock(16, 13, GROUND);
        setBlock(16, 14, GROUND);
        setBlock(17, 12, BLOCK_EMPTY);
        setBlock(17, 13, GROUND);
        setBlock(17, 14, GROUND);
        setBlock(18, 12, BLOCK_EMPTY);
        setBlock(18, 13, GROUND);
        setBlock(18, 14, GROUND);
        setBlock(19, 12, BLOCK_EMPTY);
        setBlock(19, 13, GROUND);
        setBlock(19, 14, GROUND);
        setBlock(20, 12, BLOCK_EMPTY);
        setBlock(20, 13, GROUND);
        setBlock(20, 14, GROUND);
        setBlock(21, 12, BLOCK_EMPTY);
        setBlock(21, 13, GROUND);
        setBlock(21, 14, GROUND);
        setBlock(22, 12, BLOCK_EMPTY);
        setBlock(22, 13, GROUND);
        setBlock(22, 14, GROUND);
        setBlock(23, 12, BLOCK_EMPTY);
        setBlock(23, 13, GROUND);
        setBlock(23, 14, GROUND);
        setBlock(24, 12, BLOCK_EMPTY);
        setBlock(24, 13, GROUND);
        setBlock(24, 14, GROUND);
        setBlock(25, 12, BLOCK_EMPTY);
        setBlock(25, 13, GROUND);
        setBlock(25, 14, GROUND);
        setBlock(26, 12, BLOCK_EMPTY);
        setBlock(26, 13, GROUND);
        setBlock(26, 14, GROUND);
        setBlock(27, 12, BLOCK_EMPTY);
        setBlock(27, 13, GROUND);
        setBlock(27, 14, GROUND);
        setBlock(28, 12, BLOCK_EMPTY);
        setBlock(28, 13, GROUND);
        setBlock(28, 14, GROUND);
        setBlock(29, 12, BLOCK_EMPTY);
        setBlock(29, 13, GROUND);
        setBlock(29, 14, GROUND);
        setBlock(30, 12, BLOCK_EMPTY);
        setBlock(30, 13, GROUND);
        setBlock(30, 14, GROUND);
        setBlock(31, 12, BLOCK_EMPTY);
        setBlock(31, 13, GROUND);
        setBlock(31, 14, GROUND);
        setBlock(32, 12, BLOCK_EMPTY);
        setBlock(32, 13, GROUND);
        setBlock(32, 14, GROUND);
        setBlock(33, 12, BLOCK_EMPTY);
        setBlock(33, 13, GROUND);
        setBlock(33, 14, GROUND);
        setBlock(34, 12, BLOCK_EMPTY);
        setBlock(34, 13, GROUND);
        setBlock(34, 14, GROUND);
        setBlock(35, 12, BLOCK_EMPTY);
        setBlock(35, 13, GROUND);
        setBlock(35, 14, GROUND);
        setBlock(36, 12, BLOCK_EMPTY);
        setBlock(36, 13, GROUND);
        setBlock(36, 14, GROUND);
        setBlock(37, 12, BLOCK_EMPTY);
        setBlock(37, 13, GROUND);
        setBlock(37, 14, GROUND);
        setBlock(38, 12, BLOCK_EMPTY);
        setBlock(38, 13, GROUND);
        setBlock(38, 14, GROUND);
        setBlock(39, 12, BLOCK_EMPTY);
        setBlock(39, 13, GROUND);
        setBlock(39, 14, GROUND);
        setBlock(40, 12, BLOCK_EMPTY);
        setBlock(40, 13, GROUND);
        setBlock(40, 14, GROUND);
        setBlock(41, 12, BLOCK_EMPTY);
        setBlock(41, 13, GROUND);
        setBlock(41, 14, GROUND);
        setBlock(42, 12, BLOCK_EMPTY);
        setBlock(42, 13, GROUND);
        setBlock(42, 14, GROUND);
        setBlock(43, 12, BLOCK_EMPTY);
        setBlock(43, 13, GROUND);
        setBlock(43, 14, GROUND);
        setBlock(44, 12, BLOCK_EMPTY);
        setBlock(44, 13, GROUND);
        setBlock(44, 14, GROUND);
        setBlock(45, 12, BLOCK_EMPTY);
        setBlock(45, 13, GROUND);
        setBlock(45, 14, GROUND);
        setBlock(46, 12, BLOCK_EMPTY);
        setBlock(46, 13, GROUND);
        setBlock(46, 14, GROUND);
        setBlock(47, 12, BLOCK_EMPTY);
        setBlock(47, 13, GROUND);
        setBlock(47, 14, GROUND);
        setBlock(48, 12, BLOCK_EMPTY);
        setBlock(48, 13, GROUND);
        setBlock(48, 14, GROUND);
        setBlock(49, 12, BLOCK_EMPTY);
        setBlock(49, 13, GROUND);
        setBlock(49, 14, GROUND);
        setBlock(50, 12, BLOCK_EMPTY);
        setBlock(50, 13, GROUND);
        setBlock(50, 14, GROUND);
        setBlock(51, 12, BLOCK_EMPTY);
        setBlock(51, 13, GROUND);
        setBlock(51, 14, GROUND);
        setBlock(52, 12, BLOCK_EMPTY);
        setBlock(52, 13, GROUND);
        setBlock(52, 14, GROUND);
        setBlock(53, 12, BLOCK_EMPTY);
        setBlock(53, 13, GROUND);
        setBlock(53, 14, GROUND);
        setBlock(54, 12, BLOCK_EMPTY);
        setBlock(54, 13, GROUND);
        setBlock(54, 14, GROUND);
        setBlock(55, 12, BLOCK_EMPTY);
        setBlock(55, 13, GROUND);
        setBlock(55, 14, GROUND);
        setBlock(56, 12, BLOCK_EMPTY);
        setBlock(56, 13, GROUND);
        setBlock(56, 14, GROUND);
        setBlock(57, 12, BLOCK_EMPTY);
        setBlock(57, 13, GROUND);
        setBlock(57, 14, GROUND);
        setBlock(58, 12, BLOCK_EMPTY);
        setBlock(58, 13, GROUND);
        setBlock(58, 14, GROUND);
        setBlock(59, 12, BLOCK_EMPTY);
        setBlock(59, 13, GROUND);
        setBlock(59, 14, GROUND);
        setBlock(60, 12, BLOCK_EMPTY);
        setBlock(60, 13, GROUND);
        setBlock(60, 14, GROUND);
        setBlock(61, 12, BLOCK_EMPTY);
        setBlock(61, 13, GROUND);
        setBlock(61, 14, GROUND);
        setBlock(62, 12, BLOCK_EMPTY);
        setBlock(62, 13, GROUND);
        setBlock(62, 14, GROUND);
        setBlock(63, 12, BLOCK_EMPTY);
        setBlock(63, 13, GROUND);
        setBlock(63, 14, GROUND);
        setBlock(64, 12, BLOCK_EMPTY);
        setBlock(64, 13, GROUND);
        setBlock(64, 14, GROUND);
        setBlock(65, 12, BLOCK_EMPTY);
        setBlock(65, 13, GROUND);
        setBlock(65, 14, GROUND);
        setBlock(66, 12, BLOCK_EMPTY);
        setBlock(66, 13, GROUND);
        setBlock(66, 14, GROUND);
        setBlock(67, 12, BLOCK_EMPTY);
        setBlock(67, 13, GROUND);
        setBlock(67, 14, GROUND);
        setBlock(68, 12, BLOCK_EMPTY);
        setBlock(68, 13, GROUND);
        setBlock(68, 14, GROUND);
        setBlock(69, 12, BLOCK_EMPTY);
        setBlock(69, 13, GROUND);
        setBlock(69, 14, GROUND);
        setBlock(70, 12, BLOCK_EMPTY);
        setBlock(70, 13, GROUND);
        setBlock(70, 14, GROUND);
        setBlock(71, 12, BLOCK_EMPTY);
        setBlock(71, 13, GROUND);
        setBlock(71, 14, GROUND);
        setBlock(72, 12, BLOCK_EMPTY);
        setBlock(72, 13, GROUND);
        setBlock(72, 14, GROUND);
        setBlock(73, 12, BLOCK_EMPTY);
        setBlock(73, 13, GROUND);
        setBlock(73, 14, GROUND);
        setBlock(74, 12, BLOCK_EMPTY);
        setBlock(74, 13, GROUND);
        setBlock(74, 14, GROUND);
        setBlock(75, 12, BLOCK_EMPTY);
        setBlock(75, 13, GROUND);
        setBlock(75, 14, GROUND);
        setBlock(76, 12, BLOCK_EMPTY);
        setBlock(76, 13, GROUND);
        setBlock(76, 14, GROUND);
        setBlock(77, 12, BLOCK_EMPTY);
        setBlock(77, 13, GROUND);
        setBlock(77, 14, GROUND);
        setBlock(78, 12, BLOCK_EMPTY);
        setBlock(78, 13, GROUND);
        setBlock(78, 14, GROUND);
        setBlock(79, 12, BLOCK_EMPTY);
        setBlock(79, 13, GROUND);
        setBlock(79, 14, GROUND);
        setBlock(80, 12, BLOCK_EMPTY);
        setBlock(80, 13, GROUND);
        setBlock(80, 14, GROUND);
        setBlock(81, 12, BLOCK_EMPTY);
        setBlock(81, 13, GROUND);
        setBlock(81, 14, GROUND);
        setBlock(82, 12, BLOCK_EMPTY);
        setBlock(82, 13, GROUND);
        setBlock(82, 14, GROUND);
        setBlock(83, 12, BLOCK_EMPTY);
        setBlock(83, 13, GROUND);
        setBlock(83, 14, GROUND);
        setBlock(84, 12, BLOCK_EMPTY);
        setBlock(84, 13, GROUND);
        setBlock(84, 14, GROUND);
        setBlock(85, 12, BLOCK_EMPTY);
        setBlock(85, 13, GROUND);
        setBlock(85, 14, GROUND);
        setBlock(86, 12, BLOCK_EMPTY);
        setBlock(86, 13, GROUND);
        setBlock(86, 14, GROUND);
        setBlock(87, 12, BLOCK_EMPTY);
        setBlock(87, 13, GROUND);
        setBlock(87, 14, GROUND);
        setBlock(88, 12, BLOCK_EMPTY);
        setBlock(88, 13, GROUND);
        setBlock(88, 14, GROUND);
        setBlock(89, 12, BLOCK_EMPTY);
        setBlock(89, 13, GROUND);
        setBlock(89, 14, GROUND);
        setBlock(90, 12, BLOCK_EMPTY);
        setBlock(90, 13, GROUND);
        setBlock(90, 14, GROUND);
        setBlock(91, 12, BLOCK_EMPTY);
        setBlock(91, 13, GROUND);
        setBlock(91, 14, GROUND);
        setBlock(92, 12, BLOCK_EMPTY);
        setBlock(92, 13, GROUND);
        setBlock(92, 14, GROUND);
        setBlock(93, 12, BLOCK_EMPTY);
        setBlock(93, 13, GROUND);
        setBlock(93, 14, GROUND);
        setBlock(94, 12, BLOCK_EMPTY);
        setBlock(94, 13, GROUND);
        setBlock(94, 14, GROUND);
        setBlock(95, 12, BLOCK_EMPTY);
        setBlock(95, 13, GROUND);
        setBlock(95, 14, GROUND);
        setBlock(96, 12, BLOCK_EMPTY);
        setBlock(96, 13, GROUND);
        setBlock(96, 14, GROUND);
        setBlock(97, 12, BLOCK_EMPTY);
        setBlock(97, 13, GROUND);
        setBlock(97, 14, GROUND);
        setBlock(98, 12, BLOCK_EMPTY);
        setBlock(98, 13, GROUND);
        setBlock(98, 14, GROUND);
        setBlock(99, 12, BLOCK_EMPTY);
        setBlock(99, 13, GROUND);
        setBlock(99, 14, GROUND);
        setSpriteTemplate(92, 8, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(90, 8, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(84, 6, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(82, 6, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(77, 6, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(74, 8, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(70, 8, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(68, 5, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(62, 6, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(54, 6, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(45, 7, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(39, 9, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(38, 7, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(33, 4, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(30, 5, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(22, 6, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(8, 9, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setSpriteTemplate(6, 9, new SpriteTemplate(Enemy.ENEMY_GREEN_KOOPA, false));
        setBlock(0, 11, HILL_TOP);
        setBlock(1, 14, HILL_TOP);
        setBlock(2, 13, HILL_TOP);
        setBlock(3, 13, HILL_TOP);
        setBlock(4, 13, HILL_TOP);
        setBlock(5, 13, HILL_TOP);
        setBlock(6, 13, HILL_TOP);
        setBlock(7, 13, HILL_TOP);
        setBlock(8, 13, HILL_TOP);
        setBlock(9, 13, HILL_TOP);
        setBlock(10, 13, HILL_TOP);
        setBlock(11, 13, HILL_TOP);
        setBlock(12, 13, HILL_TOP);
        setBlock(13, 13, HILL_TOP);
        setBlock(14, 13, HILL_TOP);
        setBlock(15, 13, HILL_TOP);
        setBlock(16, 13, HILL_TOP);
        setBlock(17, 13, HILL_TOP);
        setBlock(18, 13, HILL_TOP);
        setBlock(19, 13, HILL_TOP);
        setBlock(20, 13, HILL_TOP);
        setBlock(21, 13, HILL_TOP);
        setBlock(22, 13, HILL_TOP);
        setBlock(23, 13, HILL_TOP);
        setBlock(24, 13, HILL_TOP);
        setBlock(25, 13, HILL_TOP);
        setBlock(26, 13, HILL_TOP);
        setBlock(27, 13, HILL_TOP);
        setBlock(28, 13, HILL_TOP);
        setBlock(29, 13, HILL_TOP);
        setBlock(30, 13, HILL_TOP);
        setBlock(31, 13, HILL_TOP);
        setBlock(32, 13, HILL_TOP);
        setBlock(33, 13, HILL_TOP);
        setBlock(34, 13, HILL_TOP);
        setBlock(35, 13, HILL_TOP);
        setBlock(36, 13, HILL_TOP);
        setBlock(37, 13, HILL_TOP);
        setBlock(38, 13, HILL_TOP);
        setBlock(39, 13, HILL_TOP);
        setBlock(40, 13, HILL_TOP);
        setBlock(41, 13, HILL_TOP);
        setBlock(42, 13, HILL_TOP);
        setBlock(43, 13, HILL_TOP);
        setBlock(44, 13, HILL_TOP);
        setBlock(45, 13, HILL_TOP);
        setBlock(46, 13, HILL_TOP);
        setBlock(47, 13, HILL_TOP);
        setBlock(48, 13, HILL_TOP);
        setBlock(49, 13, HILL_TOP);
        setBlock(50, 13, HILL_TOP);
        setBlock(51, 13, HILL_TOP);
        setBlock(52, 13, HILL_TOP);
        setBlock(53, 13, HILL_TOP);
        setBlock(54, 13, HILL_TOP);
        setBlock(55, 13, HILL_TOP);
        setBlock(56, 13, HILL_TOP);
        setBlock(57, 13, HILL_TOP);
        setBlock(58, 13, HILL_TOP);
        setBlock(59, 13, HILL_TOP);
        setBlock(60, 13, HILL_TOP);
        setBlock(61, 13, HILL_TOP);
        setBlock(62, 13, HILL_TOP);
        setBlock(63, 13, HILL_TOP);
        setBlock(64, 13, HILL_TOP);
        setBlock(65, 13, HILL_TOP);
        setBlock(66, 13, HILL_TOP);
        setBlock(67, 13, HILL_TOP);
        setBlock(68, 13, HILL_TOP);
        setBlock(69, 13, HILL_TOP);
        setBlock(70, 13, HILL_TOP);
        setBlock(71, 13, HILL_TOP);
        setBlock(72, 13, HILL_TOP);
        setBlock(73, 13, HILL_TOP);
        setBlock(74, 13, HILL_TOP);
        setBlock(75, 13, HILL_TOP);
        setBlock(76, 13, HILL_TOP);
        setBlock(77, 13, HILL_TOP);
        setBlock(78, 13, HILL_TOP);
        setBlock(79, 13, HILL_TOP);
        setBlock(80, 13, HILL_TOP);
        setBlock(81, 13, HILL_TOP);
        setBlock(82, 13, HILL_TOP);
        setBlock(83, 13, HILL_TOP);
        setBlock(84, 13, HILL_TOP);
        setBlock(85, 13, HILL_TOP);
        setBlock(86, 13, HILL_TOP);
        setBlock(87, 13, HILL_TOP);
        setBlock(88, 13, HILL_TOP);
        setBlock(89, 13, HILL_TOP);
        setBlock(90, 13, HILL_TOP);
        setBlock(91, 13, HILL_TOP);
        setBlock(92, 13, HILL_TOP);
        setBlock(93, 13, HILL_TOP);
        setBlock(94, 13, HILL_TOP);
        setBlock(95, 13, HILL_TOP);
        setBlock(96, 13, HILL_TOP);
        setBlock(97, 13, HILL_TOP);
        setBlock(98, 13, HILL_TOP);
        setBlock(99, 13, HILL_TOP);

        xExit = 98;
        yExit = 14;
    }
}
