package dk.itu.mario.level;

import java.util.Random;

import dk.itu.mario.MarioInterface.Constraints;
import dk.itu.mario.MarioInterface.GamePlay;
import dk.itu.mario.MarioInterface.LevelInterface;
import dk.itu.mario.engine.sprites.SpriteTemplate;
import dk.itu.mario.engine.sprites.Enemy;

public class MyLevel extends Level
{
    private static long lastSeed;
    private static Random levelSeedRandom;

    private int difficulty;
    private int type;

    public MyLevel(int width, int height)
    {
        super(width, height);
    }

    public MyLevel(int width, int height, long seed, int difficulty, int type, GamePlay playerMetrics)
    {
        this(width, height);
        this.difficulty = difficulty;
        this.type = type;
        lastSeed = seed;
        levelSeedRandom = new Random(seed);

        setSpriteTemplate(27, 7, new SpriteTemplate(Enemy.ENEMY_GOOMBA, false));
        setSpriteTemplate(31, 7, new SpriteTemplate(Enemy.ENEMY_GOOMBA, false));
        setBlock(18, 13, GROUND);
        setBlock(18, 14, GROUND);
        setBlock(19, 13, GROUND);
        setBlock(19, 14, GROUND);
        setBlock(20, 13, GROUND);
        setBlock(20, 14, GROUND);
        setBlock(21, 13, GROUND);
        setBlock(21, 14, GROUND);
        setBlock(22, 13, GROUND);
        setBlock(22, 14, GROUND);
        setBlock(23, 13, GROUND);
        setBlock(23, 14, GROUND);
        setBlock(24, 13, GROUND);
        setBlock(24, 14, GROUND);
        setBlock(25, 13, GROUND);
        setBlock(25, 14, GROUND);
        setBlock(26, 13, GROUND);
        setBlock(26, 14, GROUND);
        setBlock(27, 13, GROUND);
        setBlock(27, 14, GROUND);
        setBlock(28, 13, GROUND);
        setBlock(28, 14, GROUND);
        setBlock(56, 11, BLOCK_EMPTY);
        setBlock(57, 11, BLOCK_EMPTY);
        setBlock(56, 12, BLOCK_EMPTY);
        setBlock(57, 12, BLOCK_EMPTY);
        setBlock(56, 13, BLOCK_EMPTY);
        setBlock(57, 13, BLOCK_EMPTY);
        setBlock(71, 8, BLOCK_EMPTY);
        setBlock(71, 7, BLOCK_EMPTY);
        setBlock(72, 8, BLOCK_EMPTY);
        setBlock(72, 7, BLOCK_EMPTY);
        setBlock(19, 12, BLOCK_EMPTY);
        setBlock(19, 11, BLOCK_EMPTY);
        setBlock(19, 10, BLOCK_EMPTY);
        setBlock(19, 9, BLOCK_EMPTY);
        setBlock(19, 8, BLOCK_EMPTY);
        setBlock(19, 7, BLOCK_EMPTY);
        setBlock(19, 6, BLOCK_EMPTY);
        setBlock(19, 0, BLOCK_EMPTY);
        setBlock(19, 1, BLOCK_EMPTY);
        setBlock(19, 2, BLOCK_EMPTY);
        setBlock(19, 3, BLOCK_EMPTY);
        setBlock(19, 4, BLOCK_EMPTY);
        setBlock(19, 5, BLOCK_EMPTY);
        setBlock(20, 0, BLOCK_EMPTY);
        setBlock(20, 1, BLOCK_EMPTY);
        setBlock(20, 2, BLOCK_EMPTY);
        setBlock(20, 3, BLOCK_EMPTY);
        setBlock(20, 4, BLOCK_EMPTY);
        setBlock(20, 5, BLOCK_EMPTY);
        setBlock(20, 6, BLOCK_EMPTY);
        setBlock(20, 7, BLOCK_EMPTY);
        setBlock(20, 8, BLOCK_EMPTY);
        setBlock(20, 9, BLOCK_EMPTY);
        setBlock(20, 10, BLOCK_EMPTY);
        setBlock(20, 11, BLOCK_EMPTY);
        setBlock(20, 12, BLOCK_EMPTY);
        setBlock(0, 13, GROUND);
        setBlock(1, 13, GROUND);
        setBlock(2, 13, GROUND);
        setBlock(3, 13, GROUND);
        setBlock(4, 13, GROUND);
        setBlock(5, 13, GROUND);
        setBlock(6, 13, GROUND);
        setBlock(7, 13, GROUND);
        setBlock(8, 13, GROUND);
        setBlock(9, 13, GROUND);
        setBlock(10, 13, GROUND);
        setBlock(11, 13, GROUND);
        setBlock(12, 13, GROUND);
        setBlock(13, 13, GROUND);
        setBlock(14, 13, GROUND);
        setBlock(15, 13, GROUND);
        setBlock(16, 13, GROUND);
        setBlock(16, 12, GROUND);
        setBlock(17, 12, GROUND);
        setBlock(17, 13, GROUND);
        setBlock(17, 14, GROUND);
        setBlock(16, 14, GROUND);
        setBlock(15, 14, GROUND);
        setBlock(14, 14, GROUND);
        setBlock(13, 14, GROUND);
        setBlock(12, 14, GROUND);
        setBlock(11, 14, GROUND);
        setBlock(10, 14, GROUND);
        setBlock(9, 14, GROUND);
        setBlock(8, 14, GROUND);
        setBlock(7, 14, GROUND);
        setBlock(6, 14, GROUND);
        setBlock(5, 14, GROUND);
        setBlock(4, 14, GROUND);
        setBlock(3, 14, GROUND);
        setBlock(2, 14, GROUND);
        setBlock(1, 14, GROUND);
        setBlock(0, 14, GROUND);
        setBlock(0, 12, GROUND);
        setBlock(0, 11, GROUND);
        setBlock(1, 11, GROUND);
        setBlock(2, 11, GROUND);
        setBlock(3, 11, GROUND);
        setBlock(4, 11, GROUND);
        setBlock(5, 11, GROUND);
        setBlock(6, 11, GROUND);
        setBlock(7, 11, GROUND);
        setBlock(8, 11, GROUND);
        setBlock(9, 11, GROUND);
        setBlock(8, 12, GROUND);
        setBlock(7, 12, GROUND);
        setBlock(6, 12, GROUND);
        setBlock(5, 12, GROUND);
        setBlock(4, 12, GROUND);
        setBlock(3, 12, GROUND);
        setBlock(2, 12, GROUND);
        setBlock(1, 12, GROUND);
        setBlock(9, 12, GROUND);
        setBlock(10, 12, GROUND);
        setBlock(11, 12, GROUND);
        setBlock(12, 12, GROUND);
        setBlock(12, 11, GROUND);
        setBlock(13, 11, GROUND);
        setBlock(14, 11, GROUND);
        setBlock(15, 11, GROUND);
        setBlock(16, 11, GROUND);
        setBlock(17, 11, GROUND);
        setBlock(18, 12, GROUND);
        setBlock(18, 11, GROUND);
        setBlock(15, 12, GROUND);
        setBlock(14, 12, GROUND);
        setBlock(13, 12, GROUND);
        setBlock(11, 11, GROUND);
        setBlock(10, 11, GROUND);
        setBlock(26, 12, BLOCK_EMPTY);
        setBlock(27, 11, BLOCK_EMPTY);
        setBlock(27, 12, BLOCK_EMPTY);
        setBlock(28, 11, BLOCK_EMPTY);
        setBlock(28, 12, BLOCK_EMPTY);
        setBlock(28, 10, BLOCK_EMPTY);
        setBlock(29, 9, BLOCK_EMPTY);
        setBlock(29, 10, BLOCK_EMPTY);
        setBlock(29, 11, BLOCK_EMPTY);
        setBlock(29, 12, BLOCK_EMPTY);
        setBlock(30, 10, BLOCK_EMPTY);
        setBlock(30, 11, BLOCK_EMPTY);
        setBlock(63, 13, GROUND);
        setBlock(63, 14, GROUND);
        setBlock(65, 14, BLOCK_EMPTY);
        setBlock(66, 14, BLOCK_EMPTY);
        setBlock(66, 13, BLOCK_EMPTY);
        setBlock(0, 11, HILL_TOP);
        setBlock(1, 11, HILL_TOP);
        setBlock(2, 11, HILL_TOP);
        setBlock(3, 11, HILL_TOP);
        setBlock(4, 11, HILL_TOP);
        setBlock(5, 11, HILL_TOP);
        setBlock(6, 11, HILL_TOP);
        setBlock(7, 11, HILL_TOP);
        setBlock(8, 11, HILL_TOP);
        setBlock(9, 11, HILL_TOP);
        setBlock(10, 11, HILL_TOP);
        setBlock(11, 11, HILL_TOP);
        setBlock(12, 11, HILL_TOP);
        setBlock(13, 11, HILL_TOP);
        setBlock(14, 11, HILL_TOP);
        setBlock(15, 11, HILL_TOP);
        setBlock(16, 11, HILL_TOP);
        setBlock(17, 11, HILL_TOP);
        setBlock(18, 11, HILL_TOP);
        setBlock(19, 13, HILL_TOP);
        setBlock(20, 13, HILL_TOP);
        setBlock(21, 13, HILL_TOP);
        setBlock(22, 13, HILL_TOP);
        setBlock(23, 13, HILL_TOP);
        setBlock(24, 13, HILL_TOP);
        setBlock(25, 13, HILL_TOP);
        setBlock(26, 13, HILL_TOP);
        setBlock(27, 13, HILL_TOP);
        setBlock(28, 13, HILL_TOP);
        setBlock(63, 13, HILL_TOP);

        xExit = 71;
        yExit = 7;
    }
}
